version: 1
disable_existing_loggers: true

formatters:
    simple:
        format: "%(asctime)s:%(levelname)s:%(funcName)s:%(message)s"

handlers:
    console:
        class: logging.StreamHandler
        level: INFO
        formatter: simple
        stream: ext://sys.stdout

    logfile:
        class: logging.handlers.TimedRotatingFileHandler
        level: DEBUG
        formatter: simple
        when: D
        filename: ./log/move.log
        backupCount: 20

root:
    level: DEBUG
    handlers: [console, logfile]